#ifndef SIZES_H
#define SIZES_H

// sizes for widgets
enum class Sizes {
    MAIN_WINDOW_WIDTH = 675,
    MAIN_WINDOW_HEIGHT = 615,
    ADD_WORD_DIALOG_WIDTH = 509,
    ADD_WORD_DIALOG_HEIGHT = 108,
    TEMP_MESSAGE_BOX_WIDTH = 75,
    TEMP_MESSAGE_BOX_HEIGHT = 50,
    MAIN_WINDOW_IMAGE_LABEL = 626
};

#endif // SIZES_H
