#ifndef SIZES_H
#define SIZES_H

// sizes for widgets
enum class Sizes {
    MAIN_WINDOW_WIDTH = 675,
    MAIN_WINDOW_HEIGHT = 615,
    ADD_WORD_DIALOG_WIDTH = 509,
    ADD_WORD_DIALOG_HEIGHT = 108,
    TEMP_MESSAGE_BOX_WIDTH = 75,
    TEMP_MESSAGE_BOX_HEIGHT = 50,
    MAIN_WINDOW_IMAGE_LABEL = 626,
    DIALOG_WINDOW_WIDTH = 600,
    DIALOG_WINDOW_HEIGHT = 200,
    CHANGE_MODE_DIALOG_WIDTH = 190,
    CHANGE_MODE_DOALOG_HEIGHT = 100,
    STATS_DIALOG_WIDTH = 180,
    STATS_DIALOG_HEIGHT = 210
};

#endif // SIZES_H
